config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('src.apps.home.urls', namespace='home')),
    path('admin/', admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/apps/account/urls.py
from django.urls import path
from .views import AccountView

app_name = 'account'

urlpatterns = [
    path('<slug:slug>/', AccountView.as_view(), name='account_page'),
]

src/apps/home/urls.py
from django.urls import path, include
from .views import (
    home,
    LoginView,
    logOut,
    RegisterUser,
)
app_name = 'home'


urlpatterns = [
    path('', home, name='home_page'),
    path('account/', include('src.apps.account.urls', namespace='account')),
    path('register/', RegisterUser.as_view(), name='register_page'),
    path('logout/', logOut, name='logout_page'),
    path('login/', LoginView.as_view(), name='login_page'),
]

src/models/accounts/models.py
from django.db import models
from django.shortcuts import reverse
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.contrib.auth import get_user_model


User = get_user_model()


class Account(models.Model):
    user         = models.OneToOneField(User, on_delete=models.CASCADE)
    slug         = models.SlugField(unique=True)
    avatar       = models.ImageField(upload_to='avatar/', blank=True, null=True)


    def __str__(self):
        return f"Это аккаунт юзера {self.user.username}"


    def get_absolute_url(self):
        return reverse('home:account:account_page', kwargs={'slug' : self.slug})


def pre_save_account_receiver(sender, instance, *args, **kwargs):
    slug = slugify(instance.user.username)
    instance.slug = slug

pre_save.connect(pre_save_account_receiver, sender=Account)

src/apps/account/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic.detail import DetailView
from src.models.accounts.models import Account


class AccountView(DetailView):
    template_name   = 'account/index.html'
    queryset        = Account.objects.all()


    def get_object(self):
        slug_    = self.kwargs.get('slug')
        return get_object_or_404(Account, slug=slug_)

src/apps/home/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib.auth import authenticate, login, logout


def logOut(request):
    logout(request)
    return redirect('home:home_page')



def home(request):
    return render(request, 'home/index.html', {})



class RegisterUser(View):

    def get(self, request, *args ,**kwargs):
        if request.user.is_authenticated:
            return redirect('home:home_page')
        return render(request, 'home/register.html', {})


class LoginView(View):
    ''' Отображение страницы входа  '''
    def get(sefl, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('home:home_page')
        return render(request, 'home/login.html', {})

    ''' Метод пост для проверки существования юзера и вход '''
    def post(sefl, request, *args, **kwargs):
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('home:home_page')
        else:
            return redirect('home:login_page')

src/apps/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title> BASE PAGE </title>
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300,700" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'style/style.css' %}">
    </head>
    <body>
        {% include 'header.html' %}
        {% block content %}

        {% endblock %}
    </body>
</html>

src/apps/templates/header.html
<div class="header_container">

    <div class='header_logo'>
        <a href="">GOBUSSINES</a>
        <form>
            <input type="text" placeholder="Поиск ..." name="" value="">
        </form>
    </div>

    <div class="header_menu">
        <a href="">все публикаций</a>
        <a href="">топ публикаций </a>
        <a href="">поиск партнера</a>
        <a href="">обсуждение идей</a>
    </div>

    <div class="header_login_and_register">
        {% if user.is_authenticated %}
            <div class='user_authenticated'>
                <a href="{{user.account.get_absolute_url}}">
                    <img src="{{user.account.avatar.url}}" width="30" height="30" />
                </a>
                <a class='btn_logout' href="{% url 'home:logout_page' %}">выйти</a>
            </div>
        {% else %}
            <div class='user_is_not_login'>
                <a href="{% url 'home:register_page' %}">регистрация</a>
                <a href="{% url 'home:login_page' %}">войти</a>
            </div>
        {% endif %}
    </div>

</div>

src/apps/templates/home/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <div class="main_container">
        <div class='main_container_posts'>
            <div class="posts">
                <div class='user_profile_img'>
                    <img src="https://pp.userapi.com/c845521/v845521265/1958c1/Pwk8qgTbAog.jpg" width="20" height="20" />
                    <a href="">Eugene</a>
                </div>
                <div class='post_info_title'>
                    <a href="">Ищем в команду маркетолога , кто согласен поработать за идею пишите.</a>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
                </div>
                <div class="post_comments_views">
                    <div class='comments'>
                        <img src="{% static './img/comment.png' %}" /><span>13</span>
                    </div>
                    <div class='vote'>
                        <img src="{% static './img/vote.png' %}"/><span>2</span>
                    </div>
                    <div class='view'>
                        <img src="{% static './img/eye.png' %}"/><span>2121</span>
                    </div>
                </div>
                <div class="post_info">
                    <a href="">поиск партнера</a>
                </div>
            </div>
            <div class="posts">
                <div class='user_profile_img'>
                    <img src="https://pp.userapi.com/c845521/v845521265/1958c1/Pwk8qgTbAog.jpg" width="20" height="20" />
                    <a href="">Eugene</a>
                </div>
                <div class='post_info_title'>
                    <a href="">Ищем в команду маркетолога , кто согласен поработать за идею пишите.</a>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
                </div>
                <div class="post_comments_views">
                    <div class='comments'>
                        <img src="{% static './img/comment.png' %}" /><span>13</span>
                    </div>
                    <div class='vote'>
                        <img src="{% static './img/vote.png' %}"/><span>2</span>
                    </div>
                    <div class='view'>
                        <img src="{% static './img/eye.png' %}"/><span>2121</span>
                    </div>
                </div>
                <div class="post_info">
                    <a href="">поиск партнера</a>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

src/apps/templates/home/login.html
{% extends 'base.html' %}


{% block content %}

    <div class='logn_container'>
        <p>Введи логин и пароль что бы войти в профиль.</p>
        <form method="POST">{% csrf_token %}
            <input type="text" name="username" placeholder="Логин ..." value="">
            <input type="password" name="password" placeholder="Пароль ..." value="">
            <button type="submit" name="button">Войти</button>
        </form>
    </div>

{% endblock %}

src/apps/templates/home/register.html
{% extends 'base.html' %}


{% block content %}

    <div class="register_container">
        <p> Заполните пожалуйста поля. </p>
        <form method="post" enctype="multipart/form-data">{% csrf_token %}
            <input type="file" name="avatar" value="">
            <input type="text" placeholder="Логин ..." name="username" value="">
            <input type="text" placeholder="Пароль ...." name="" value="">
            <button type="submit" name="button">Регистрация</button>
        </form>
    </div>

{% endblock %}